name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint and build
        run: pnpm lint && pnpm build

      # - name: Create Release Pull Request
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     version: pnpm changeset version
      #     commit: "chore: version packages"
      #     title: "chore: version packages"
      #   env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}